/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inicio;

import ARBOLAVL.Nodo;
import ARBOLB.Llave;
import TABLA_HASH.Usuario;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.LinkedList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 *
 * @author Home
 */
public class _cUsuario extends javax.swing.JFrame {

    /**
     * Creates new form Cliente
     */
    public LinkedList<Llave> _Llave;

    public _cUsuario() {
        initComponents();

        String directorio = System.getProperty("user.dir");

        ImageIcon img1 = new ImageIcon(directorio + "\\THash.jpg");
        Icon icono = new ImageIcon(img1.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_DEFAULT));
        jLabel2.setIcon(icono);
        this.repaint();

        ImageIcon img2 = new ImageIcon(directorio + "\\avl.jpg");
        Icon icono2 = new ImageIcon(img2.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_DEFAULT));
        jLabel1.setIcon(icono2);
        this.repaint();
//        Icon icon = new ImageIcon("C:\\Users\\Home\\Documents\\GitHub\\EDD_1S2020_PY2_201800634\\[EDD]Proyecto2_201800634\\avl.jpg");
//        jLabel1.setIcon(icon);

        // TODO add your handling code here:
//        try {
//            SOCKETS._cUsuario c = new SOCKETS._cUsuario();
//            Scanner sc= new Scanner(System.in);
//            String aux="";
//            while (!aux.equalsIgnoreCase("Close")) {
//                System.out.println("ESCRIBA SU OPCION");
//                aux=sc.nextLine();
//                if (aux.equalsIgnoreCase("MESSAGE")) {
//                    System.out.println("MENSAJE DEL SERVIDOR"+ c.recibirMensaje());
//                }
//            }sc.close();
//            c.CerraConexio();
//        } catch (IOException ex) {
//            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        _BISBN = new javax.swing.JTextField();
        _Combo_Catalogo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        _Lista_Libros = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        _BNOMBRE = new javax.swing.JTextField();
        jButton15 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        _ISBM = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        _TITULO = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        _AUTOR = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        _EDITORIAL = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        _ANIO = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        _EDICION = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        _CATEGORIA = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        _IDIOMA = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        _DIR_LIBROS = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        _NCATEGORIA = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        _NCARNET = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        _NOMBRE = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        _APELLIDO = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        _CARRERA = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        _PASSWORD = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        _DIR_USUARIO = new javax.swing.JTextField();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton10.setText("PREORDER");

        jButton11.setText("INORDER");

        jButton12.setText("POSTORDER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane5.addTab("REPORTES", jPanel1);

        jButton1.setText("BORRAR ISBM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("CATÁLOGO");

        jButton2.setText("VER CATÁLOGO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(_Lista_Libros);

        jButton3.setText("VER INFO");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jButton13.setText("VER LIBROS");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("DAR DE BAJA");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("BUSCAR LIBROS");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton13)
                        .addGap(28, 28, 28)
                        .addComponent(jButton3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(258, 258, 258))
                    .addComponent(_Combo_Catalogo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(_BNOMBRE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(_BISBN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addGap(64, 64, 64))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(jButton15)))
                        .addContainerGap(96, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(_Combo_Catalogo))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_BISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_BNOMBRE, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton13)
                    .addComponent(jButton3)
                    .addComponent(jButton15))
                .addContainerGap())
        );

        jTabbedPane5.addTab("CATALOGO DE LIBROS", jPanel2);

        jLabel4.setText("ISBM:");

        jLabel5.setText("Titulo:");

        jLabel6.setText("Autor:");

        jLabel7.setText("Editorial:");

        jLabel8.setText("Año:");

        jLabel9.setText("Edicion:");

        jLabel10.setText("Categoria");

        jLabel11.setText("Idioma:");

        jButton4.setText("CARGA DE LIBROS | *.json");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        _DIR_LIBROS.setEditable(false);

        jButton5.setText("CREAR LIBRO");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton9.setText("CREAR CATEGORÍA");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(_IDIOMA, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(_CATEGORIA, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(_EDICION, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(_ANIO, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(_EDITORIAL, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(_AUTOR, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(_TITULO, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(_ISBM, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_DIR_LIBROS, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(_NCATEGORIA)))
                .addGap(34, 34, 34))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_ISBM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_TITULO, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_AUTOR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_NCATEGORIA, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(_DIR_LIBROS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_EDITORIAL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_ANIO, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_EDICION, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_CATEGORIA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_IDIOMA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("OPERACION DE LIBROS", jPanel5);

        jLabel12.setText("NO. CARNET");

        jLabel13.setText("NOMBRE");

        _APELLIDO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _APELLIDOActionPerformed(evt);
            }
        });

        jLabel14.setText("APELLIDO");

        jLabel15.setText("CARRERA");

        jLabel16.setText("PASSWORD");

        jButton6.setText("CREAR USUARIO");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("MODIFICAR USUARIO");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("ELIMINAR USUARIO");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton16.setText("REPORTE USUARIOS");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        _DIR_USUARIO.setEditable(false);

        jButton17.setText("CARGA DE USUARIOS | *.json");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setText("MOSTRAR USUARIO");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(_PASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(_CARRERA, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(_APELLIDO, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(_NOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(_NCARNET, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_DIR_USUARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(_NCARNET, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(_NOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(_APELLIDO, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(_CARRERA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(_PASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton17)
                    .addComponent(_DIR_USUARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("OPERACION DE USUARIOS", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if (!_NCATEGORIA.getText().equals("")) {
            Sesion._ArbolAVL.Insertar(_NCATEGORIA.getText(), Sesion._User.getCarnet());
        } else {
            JOptionPane.showMessageDialog(null, "CATEGORIA VACÍA ", "HABISO", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            Sesion._ArbolAVL.Insertar(_CATEGORIA.getText(), 0);
            Sesion._ArbolAVL.AgregarLibro(_CATEGORIA.getText(), new Llave(Integer.parseInt(_ISBM.getText()), _TITULO.getText(),
                    _AUTOR.getText(), _EDITORIAL.getText(), Integer.parseInt(_ANIO.getText()), _EDICION.getText(), _CATEGORIA.getText(),
                    _IDIOMA.getText(), Sesion._User.getCarnet()));
        } catch (Exception e) {
        }

        _CATEGORIA.setText("");
        _ISBM.setText("");
        _TITULO.setText("");
        _AUTOR.setText("");
        _EDITORIAL.setText("");
        _ANIO.setText("");
        _EDICION.setText("");
        _IDIOMA.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String aux = "";
        String texto = "";
        String Ruta = "";

        /**
         * llamamos el metodo que permite cargar la ventana
         */
        JFileChooser JfC = new JFileChooser();
        JfC.setAcceptAllFileFilterUsed(false);
        JfC.setFileFilter(new FileNameExtensionFilter("Archivos con extension *.json", "json"));
        JfC.setCurrentDirectory(new File("Escritorio"));
        JfC.showOpenDialog(null);
        /**
         * abrimos el archivo seleccionado
         */
        File Archivo = JfC.getSelectedFile();
        if (Archivo != null) {
            Ruta = "" + Archivo;

            _DIR_LIBROS.setText(Ruta);
            leerLibros(Ruta);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:

        DefaultListModel modelo = new DefaultListModel();
        for (Llave llave : _Llave) {
            if (llave.getTítulo().contains(_BNOMBRE.getText())) {
                modelo.addElement(llave.getISBN() + "\t" + llave.getTítulo());
            }
        }
        _Lista_Libros.setModel(modelo);
        _BNOMBRE.setText("");
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        try {
            if (Catalogo.get(_Combo_Catalogo.getSelectedIndex()).getCarnet() == Sesion._User.getCarnet()) {
                int Seleccion = JOptionPane.showOptionDialog(null, "DESE ELIMINAR CATALOGO", "SELECCIONE UNA OPCION",
                        JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"SI", "NO"}, "SI");

                if ((Seleccion + 1) == 1) {
                    Sesion._ArbolAVL.Eliminar(Catalogo.get(_Combo_Catalogo.getSelectedIndex()).getCategoria());
                } else {
                    JOptionPane.showMessageDialog(null, "HABISO", "OPERACION CANCELADA", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "NO PUEDES ELIMINAR CATEEGORIAS DE OTROS ESTUDIANTES", "HABISO ", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (StackOverflowError | NullPointerException | IndexOutOfBoundsException e) {
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        try {

            System.out.println(_Combo_Catalogo.getItemAt(_Combo_Catalogo.getSelectedIndex()));

            _Llave = new LinkedList<>();

            Catalogo.get(_Combo_Catalogo.getSelectedIndex()).getArbolB().GenerarDot();
            Catalogo.get(_Combo_Catalogo.getSelectedIndex()).getArbolB().Lista_Llaves(_Llave);

            DefaultListModel modelo = new DefaultListModel();
            for (Llave llave : _Llave) {
                modelo.addElement(llave.getISBN() + "\t" + llave.getTítulo());
            }
            _Lista_Libros.setModel(modelo);
        } catch (StackOverflowError | NullPointerException | IndexOutOfBoundsException e) {
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("");
        try {
            jTextArea1.append("ISBN: " + _Llave.get(_Lista_Libros.getSelectedIndex()).getISBN() + "\n");
            jTextArea1.append("TITULO: " + _Llave.get(_Lista_Libros.getSelectedIndex()).getTítulo() + "\n");
            jTextArea1.append("AUTOR: " + _Llave.get(_Lista_Libros.getSelectedIndex()).getAutor() + "\n");
            jTextArea1.append("AÑO: " + _Llave.get(_Lista_Libros.getSelectedIndex()).getAnio() + "\n");
            jTextArea1.append("EDITORIAL: " + _Llave.get(_Lista_Libros.getSelectedIndex()).getEditorial() + "\n");
            jTextArea1.append("EDICION: " + _Llave.get(_Lista_Libros.getSelectedIndex()).getEdición() + "\n");
            jTextArea1.append("CATEGORIA: " + _Llave.get(_Lista_Libros.getSelectedIndex()).getCategoría() + "\n");
            jTextArea1.append("CARNET: " + _Llave.get(_Lista_Libros.getSelectedIndex()).getCarnet() + "\n");
        } catch (StackOverflowError | NullPointerException | IndexOutOfBoundsException e) {
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //        _Combo_Catalogo = new JComboBox();
        try {
            Sesion._ArbolAVL.GenerarDot();
            Catalogo = new LinkedList<>();

            _Combo_Catalogo.removeAllItems();
            llenar(Sesion._ArbolAVL.getRaiz());
            for (Nodo nodo : Catalogo) {
                _Combo_Catalogo.addItem(nodo.getCategoria());
            }
        } catch (StackOverflowError | NullPointerException | IndexOutOfBoundsException e) {
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            int _EISBN = Integer.parseInt(_BISBN.getText());
            if (Catalogo.get(_Combo_Catalogo.getSelectedIndex()).getCarnet() == Sesion._User.getCarnet()) {
                int Seleccion = JOptionPane.showOptionDialog(null, "DESE ELIMINAR CATALOGO", "SELECCIONE UNA OPCION",
                        JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"SI", "NO"}, "SI");

                if ((Seleccion + 1) == 1) {
                    Catalogo.get(_Combo_Catalogo.getSelectedIndex()).getArbolB().Eliminar(_EISBN);
                } else {
                    JOptionPane.showMessageDialog(null, "OPERACION CANCELADA", "HABISO", JOptionPane.INFORMATION_MESSAGE);
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "INGRESAR CÓDIGO ISBN", "HABISO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        Sesion._TablaHash.GenerarDot();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        String aux = "";
        String texto = "";
        String Ruta = "";

        /**
         * llamamos el metodo que permite cargar la ventana
         */
        JFileChooser JfC = new JFileChooser();
        JfC.setAcceptAllFileFilterUsed(false);
        JfC.setFileFilter(new FileNameExtensionFilter("Archivos con extension *.json", "json"));
        JfC.setCurrentDirectory(new File("Escritorio"));
        JfC.showOpenDialog(null);
        /**
         * abrimos el archivo seleccionado
         */
        File Archivo = JfC.getSelectedFile();
        if (Archivo != null) {
            Ruta = "" + Archivo;

            _DIR_USUARIO.setText(Ruta);
            leerUsuarios(Ruta);
        }

    }//GEN-LAST:event_jButton17ActionPerformed

    private void _APELLIDOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__APELLIDOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__APELLIDOActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try {
            if (!_NCARNET.getText().equals("") && !_NOMBRE.getText().equals("") && !_APELLIDO.getText().equals("")
                    && !_CARRERA.getText().equals("") && !_PASSWORD.getText().equals("")) {
                Sesion._TablaHash.Agregar(new Usuario(Integer.parseInt(_NCARNET.getText()), _NOMBRE.getText(), _APELLIDO.getText(),
                        _CARRERA.getText(), _PASSWORD.getText()));
            } else {
                JOptionPane.showMessageDialog(null, "NO DEJAR CAMPOS VACIOS", "HABISO", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "INGRESAR CARNET CORRECTO", "HABISO", JOptionPane.ERROR_MESSAGE);
        }
        _NCARNET.setText("");
        _NOMBRE.setText("");
        _APELLIDO.setText("");
        _CARRERA.setText("");
        _PASSWORD.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        try {
            Usuario _user = Sesion._TablaHash.Buscar_Usuario(Long.parseLong(_NCARNET.getText()));
            if (_user != null) {
                _NOMBRE.setText(_user.getNombre());
                _APELLIDO.setText(_user.getApellido());
                _CARRERA.setText(_user.getCarrera());
                _PASSWORD.setText(_user.getPassword());
            } else {
                JOptionPane.showMessageDialog(null, "USUARIO NO ENCONTRADO", "HABISO", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "INGRESAR CARNET CORRECTO", "HABISO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        try {
            Sesion._TablaHash.EliminarUsuario(Long.parseLong(_NCARNET.getText()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "INGRESAR CARNET CORRECTO", "HABISO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try {
            Usuario _user = Sesion._TablaHash.Buscar_Usuario(Long.parseLong(_NCARNET.getText()));
            if (_user != null) {
                _user.setNombre(_NOMBRE.getText());
                _user.setApellido(_APELLIDO.getText());
                _user.setCarrera(_CARRERA.getText());
                _user.setPassword(_PASSWORD.getText());
            } else {
                JOptionPane.showMessageDialog(null, "USUARIO NO ENCONTRADO", "HABISO", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "INGRESAR CARNET CORRECTO", "HABISO", JOptionPane.ERROR_MESSAGE);
        }
        
        _NCARNET.setText("");
        _NOMBRE.setText("");
        _APELLIDO.setText("");
        _CARRERA.setText("");
        _PASSWORD.setText("");
    }//GEN-LAST:event_jButton7ActionPerformed

    LinkedList<Nodo> Catalogo;

    public void leerUsuarios(String _direccion) {
        JSONParser parser = new JSONParser();

        try {

            Object obj = parser.parse(new FileReader(_direccion));
            JSONObject jsonObject = (JSONObject) parser.parse(new InputStreamReader(new FileInputStream(_direccion), "UTF-8"));
            System.out.println("JSON LEIDO: " + jsonObject);

            JSONArray array = (JSONArray) jsonObject.get("Usuarios");
            System.out.println("");

            for (int i = 0; i < array.size(); i++) {
                JSONObject jsonObject1 = (JSONObject) array.get(i);

                System.out.println("DATOS DEL USUARIO: " + i);
                System.out.println("ID: " + jsonObject1.get("Carnet"));
                System.out.println("Nombre: " + jsonObject1.get("Nombre"));
                System.out.println("Telefono: " + jsonObject1.get("Apellido"));
                System.out.println("Email: " + jsonObject1.get("Carrera"));
                System.out.println("Email: " + jsonObject1.get("Password"));

                Sesion._TablaHash.Agregar(new Usuario(Integer.parseInt(jsonObject1.get("Carnet").toString()), jsonObject1.get("Nombre").toString(), jsonObject1.get("Apellido").toString(),
                        jsonObject1.get("Carrera").toString(), jsonObject1.get("Password").toString()));

                System.out.println("");
            }

        } catch (FileNotFoundException e) {
        } catch (IOException e) {
        } catch (ParseException e) {
        }

        Sesion._TablaHash.Mostrar_TablaHash();
        Sesion._TablaHash.GenerarDot();
    }

    public void llenar(Nodo _Nodo) {
        if (_Nodo != null) {
            llenar(_Nodo.getIzquierdo());
            Catalogo.add(_Nodo);
            llenar(_Nodo.getDerecho());
        }
    }

    public void leerLibros(String _direccion) {
        JSONParser parser = new JSONParser();

        try {

            Object obj = parser.parse(new FileReader(_direccion));
            JSONObject jsonObject = (JSONObject) parser.parse(new InputStreamReader(new FileInputStream(_direccion), "UTF-8"));
//            System.out.println("JSON LEIDO: " + jsonObject);

            JSONArray array = (JSONArray) jsonObject.get("libros");
            System.out.println("");

            for (int i = 0; i < array.size(); i++) {
                JSONObject jsonObject1 = (JSONObject) array.get(i);

//                System.out.println("DATOS DE LIBROS: " + i);
//                System.out.println("ISBM: " + jsonObject1.get("ISBN"));
//                System.out.println("AÑO: " + jsonObject1.get("Año"));
//                System.out.println("IDIOMA: " + jsonObject1.get("Idioma"));
//                System.out.println("TITULO: " + jsonObject1.get("Titulo"));
//                System.out.println("EDITORIAL: " + jsonObject1.get("Editorial"));
//                System.out.println("AUTOR: " + jsonObject1.get("Autor"));
//                System.out.println("EDICION: " + jsonObject1.get("Edicion"));
//                System.out.println("CATEGORIA: " + jsonObject1.get("Categoria"));
                Sesion._ArbolAVL.Insertar(jsonObject1.get("Categoria").toString(), Sesion._User.getCarnet());
                Sesion._ArbolAVL.AgregarLibro(jsonObject1.get("Categoria").toString(),
                        new Llave(Long.parseLong(jsonObject1.get("ISBN").toString()),
                                jsonObject1.get("Titulo").toString(), jsonObject1.get("Autor").toString(),
                                jsonObject1.get("Editorial").toString(), Integer.parseInt(jsonObject1.get("Año").toString()),
                                jsonObject1.get("Edicion").toString(), jsonObject1.get("Categoria").toString(),
                                jsonObject1.get("Idioma").toString(), 0));
                System.out.println("INGRESADO " + i);

            }

        } catch (FileNotFoundException e) {
        } catch (IOException e) {
        } catch (ParseException e) {
        }
//        Sesion._ArbolAVL.PreOrder(Sesion._ArbolAVL.getRaiz());
//
//        Sesion._ArbolAVL.GenerarDot();

//        Nodo _Nodo = Sesion._ArbolAVL.Buscar("Drama", Sesion._ArbolAVL.getRaiz());
//        if (_Nodo != null) {
//            _Nodo.getArbolB().GenerarDot();
//        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(_cUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(_cUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(_cUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(_cUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new _cUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField _ANIO;
    private javax.swing.JTextField _APELLIDO;
    private javax.swing.JTextField _AUTOR;
    private javax.swing.JTextField _BISBN;
    private javax.swing.JTextField _BNOMBRE;
    private javax.swing.JTextField _CARRERA;
    private javax.swing.JTextField _CATEGORIA;
    private javax.swing.JComboBox<String> _Combo_Catalogo;
    private javax.swing.JTextField _DIR_LIBROS;
    private javax.swing.JTextField _DIR_USUARIO;
    private javax.swing.JTextField _EDICION;
    private javax.swing.JTextField _EDITORIAL;
    private javax.swing.JTextField _IDIOMA;
    private javax.swing.JTextField _ISBM;
    private javax.swing.JList<String> _Lista_Libros;
    private javax.swing.JTextField _NCARNET;
    private javax.swing.JTextField _NCATEGORIA;
    private javax.swing.JTextField _NOMBRE;
    private javax.swing.JTextField _PASSWORD;
    private javax.swing.JTextField _TITULO;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
